management:
  endpoints:
    web:
      exposure:
        include: "*"


spring:
  cloud:
    stream:
      bindings:
        output:
          producer:
            requiredGroups: messages.group.crea
          destination: crea
          group: messages.group.crea